version: 2.1
jobs:
  deploy:
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          REPO_NAME=$(git remote get-url origin | sed -E "s/.+:[0-9a-z_-]+\/([0-9a-z_-]+)(\.git)?/\1/")
          docker build -t 4p00rv/${REPO_NAME}:${CIRCLE_TAG:-latest} .
      - deploy: 
          command: |
            docker login -u 4p00rv -p $DOCKERHUB_PASSWORD
            docker push 4p00rv/${REPO_NAME}:${CIRCLE_TAG:-latest}


workflows:
  version: 2
  tagged:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - gh-pages
              tags:
                only: /.*/
